### PR TITLE
Fixing how the decorator works (now it wont need an argument)

### PR DESCRIPTION
**Pull request by brunogfranca**
New usage:

```
@route('/')
@login()
def home(auth):
    user = auth.get_user(request.environ)
    return "Home page {}".format(pformat(user))
```

### CODE REVIEW

**Comment by adammhaile** [comment]
I don't believe the demo in the readme has been update to reflect this... I have the latest code (from pip) and still get this error.

**Comment by avelino** [comment]
I'm using the bottle-auth in openmining[1] and I am not in error

[1] https://github.com/avelino/mining/blob/master/manage.py#L57

**Comment by adammhaile** [comment]
That's great, but the demo code in the README doesn't work. It should be updated.

**Comment by avelino** [comment]
@adammhaile upgrade example source https://github.com/avelino/bottle-auth#example

**Comment by adammhaile** [comment]
Thanks!

**Pull request merged**
